return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 16,
  nextobjectid = 190,
  properties = {
    ["border"] = "undertale/ruins",
    ["light"] = true,
    ["music"] = "ruins",
    ["name"] = "Ruins"
  },
  tilesets = {
    {
      name = "ruins1",
      firstgid = 1,
      filename = "../../tilesets/ruins1.tsx"
    },
    {
      name = "ruins2",
      firstgid = 153,
      filename = "../../tilesets/ruins2.tsx"
    },
    {
      name = "ruins3",
      firstgid = 249,
      filename = "../../tilesets/ruins3.tsx"
    },
    {
      name = "ruins4",
      firstgid = 321,
      filename = "../../tilesets/ruins4.tsx"
    },
    {
      name = "ruins5",
      firstgid = 361,
      filename = "../../tilesets/ruins5.tsx"
    },
    {
      name = "objects",
      firstgid = 489,
      filename = "../../tilesets/objects.tsx",
      exportfilename = "../../tilesets/objects.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 361, 361, 265, 257, 257, 265, 361, 361, 361, 0, 0, 0, 0,
        0, 0, 430, 361, 361, 273, 257, 282, 265, 361, 396, 361, 361, 0, 0, 0,
        0, 0, 430, 361, 361, 257, 257, 265, 361, 361, 392, 361, 361, 0, 0, 0,
        0, 0, 430, 361, 361, 257, 257, 265, 361, 361, 392, 361, 361, 0, 0, 0,
        0, 0, 430, 361, 361, 281, 257, 274, 265, 361, 392, 361, 361, 0, 0, 0,
        0, 0, 430, 463, 361, 265, 281, 257, 274, 361, 399, 361, 361, 0, 0, 0,
        0, 0, 0, 0, 363, 463, 265, 257, 257, 361, 361, 361, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 257, 257, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 12,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 301, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 448, 0, 0, 0, 0, 0, 0, 0, 447, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 447, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 430, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 430, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 430, 0, 0,
        0, 0, 416, 440, 0, 0, 0, 0, 0, 0, 0, 0, 439, 448, 0, 0,
        0, 0, 0, 0, 416, 440, 0, 0, 0, 0, 0, 439, 448, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 13,
      name = "Tile Layer 3",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 30, 151, 151, 152, 0, 0, 150, 23, 23, 23, 31, 0, 0, 0,
        0, 30, 152, 251, 251, 252, 0, 0, 250, 251, 251, 251, 150, 31, 0, 0,
        0, 144, 252, 251, 301, 252, 0, 0, 250, 251, 251, 251, 250, 150, 31, 0,
        0, 144, 252, 259, 259, 260, 0, 0, 258, 259, 259, 259, 250, 250, 142, 0,
        0, 144, 260, 0, 0, 0, 0, 0, 0, 0, 0, 0, 258, 250, 142, 0,
        0, 144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 258, 142, 0,
        0, 144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 142, 0,
        0, 144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 142, 0,
        0, 144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 142, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 15,
      name = "objects_deco",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 153,
          name = "ruinsdoor",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 160,
          width = 80,
          height = 120,
          rotation = 0,
          gid = 508,
          visible = true,
          properties = {
            ["flagcheck"] = "!completedRuinsRoom2Puzzle2"
          }
        },
        {
          id = 172,
          name = "tilebutton",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["blocks"] = false,
            ["cutscene"] = "undertale.ruins_2_puzzle",
            ["group"] = "ruins_2_work",
            ["keepdown"] = true,
            ["npcs"] = true,
            ["once"] = true,
            ["onsound"] = "noise",
            ["player"] = true,
            ["pressedsprite"] = "world/events/utpressed",
            ["sprite"] = "world/events/utidle"
          }
        },
        {
          id = 177,
          name = "tilebutton",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["blocks"] = false,
            ["cutscene"] = "undertale.ruins_2_puzzle",
            ["group"] = "ruins_2_work",
            ["keepdown"] = true,
            ["npcs"] = true,
            ["once"] = true,
            ["onsound"] = "noise",
            ["player"] = true,
            ["pressedsprite"] = "world/events/utpressed",
            ["sprite"] = "world/events/utidle"
          }
        },
        {
          id = 173,
          name = "tilebutton",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["blocks"] = false,
            ["cutscene"] = "undertale.ruins_2_puzzle",
            ["group"] = "ruins_2_work",
            ["keepdown"] = true,
            ["npcs"] = true,
            ["once"] = true,
            ["onsound"] = "noise",
            ["player"] = true,
            ["pressedsprite"] = "world/events/utpressed",
            ["sprite"] = "world/events/utidle"
          }
        },
        {
          id = 176,
          name = "tilebutton",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["blocks"] = false,
            ["cutscene"] = "undertale.ruins_2_puzzle",
            ["group"] = "ruins_2_work",
            ["keepdown"] = true,
            ["npcs"] = true,
            ["once"] = true,
            ["onsound"] = "noise",
            ["player"] = true,
            ["pressedsprite"] = "world/events/utpressed",
            ["sprite"] = "world/events/utidle"
          }
        },
        {
          id = 174,
          name = "tilebutton",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["blocks"] = false,
            ["group"] = "ruins_2_nowork",
            ["keepdown"] = true,
            ["npcs"] = true,
            ["once"] = false,
            ["onsound"] = "noise",
            ["player"] = true,
            ["pressedsprite"] = "world/events/utpressed",
            ["sprite"] = "world/events/utidle"
          }
        },
        {
          id = 175,
          name = "tilebutton",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["blocks"] = false,
            ["group"] = "ruins_2_nowork",
            ["keepdown"] = true,
            ["npcs"] = true,
            ["once"] = false,
            ["onsound"] = "noise",
            ["player"] = true,
            ["pressedsprite"] = "world/events/utpressed",
            ["sprite"] = "world/events/utidle"
          }
        },
        {
          id = 183,
          name = "lever",
          type = "",
          shape = "rectangle",
          x = 412,
          y = 134,
          width = 14,
          height = 30,
          rotation = 0,
          gid = 509,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 120,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["flagcheck"] = "!completedRuinsRoom2Puzzle2",
            ["solid"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 120,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 200,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 440,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 440,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 240,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "",
          type = "",
          shape = "polygon",
          x = 80,
          y = 360,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = 40 },
            { x = 0, y = 40 }
          },
          properties = {}
        },
        {
          id = 168,
          name = "",
          type = "",
          shape = "polygon",
          x = 160,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = 40 },
            { x = 0, y = 40 }
          },
          properties = {}
        },
        {
          id = 171,
          name = "",
          type = "",
          shape = "polygon",
          x = 560,
          y = 360,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -80, y = 80 },
            { x = 0, y = 80 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 178,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 80,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 151,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 116,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "up",
            ["map"] = "ruins/ruins_3",
            ["marker"] = "entryup"
          }
        },
        {
          id = 152,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 440,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "down",
            ["map"] = "ruins/ruins_1",
            ["marker"] = "entrydown"
          }
        },
        {
          id = 182,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "undertale.ruins_2_press_switch",
            ["once"] = false,
            ["solid"] = true
          }
        },
        {
          id = 185,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text1"] = "* Only the fearless may proceed.\n* Brave ones, foolish ones.\n* Both walk not the middle road"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 66,
          name = "entrydown",
          type = "",
          shape = "point",
          x = 280,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "entryup",
          type = "",
          shape = "point",
          x = 320,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "spawn",
          type = "",
          shape = "point",
          x = 240,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
